base_model: TheBloke/Mistral-7B-Instruct-v0.2-GPTQ
tokenizer_type: AutoTokenizer
model_type: AutoModelForCausalLM
trust_remote_code: true

load_in_4bit: false
load_in_8bit: false
strict: false

quantization_config:
  quant_method: gptq
  use_cuda_fp16: true
  use_exllama: false

datasets:
  - path: ./data/axolotl_dialogues.jsonl
    type: completion
    field: prompt
    completion_field: completion

val_set_size: 0
output_dir: ./out

adapter: lora
lora_model_dir: null
lora_target_modules:
  - q_proj
  - k_proj
  - v_proj
  - o_proj
  - gate_proj
  - up_proj
  - down_proj
lora_r: 8
lora_alpha: 16
lora_dropout: 0.05
gptq_use_triton: false

sequence_len: 2048
sample_packing: true
eval_sample_packing: false
pad_to_sequence_len: true

micro_batch_size: 2
gradient_accumulation_steps: 4
num_epochs: 5  # ⬅️ you can increase to 10 later
optimizer: adamw_torch
lr_scheduler: cosine
learning_rate: 2e-5
train_on_inputs: false
group_by_length: false

bf16: false
fp16: false
tf32: true

gradient_checkpointing: true
save_steps: 10
logging_steps: 5

flash_attention: false
