base_model: /root/.cache/huggingface/hub/models--TheBloke--Mixtral-8x7B-Instruct-v0.1-GPTQ/snapshots/0f81ba4680ccd2bce163334b93305d40b9e27b09
tokenizer_type: AutoTokenizer
model_type: AutoGPTQForCausalLM
trust_remote_code: true

load_in_4bit: false
load_in_8bit: false
strict: false

quantization_config:
  quant_method: gptq
  use_cuda_fp16: true
  use_exllama: false
  model_file: model.safetensors

datasets:
  - path: ./data/axolotl_dialogues.jsonl
    type: completion
    field: prompt
    completion_field: completion

val_set_size: 0
output_dir: ./out

adapter: lora
lora_model_dir: null
lora_target_modules:
  - q_proj
  - k_proj
  - v_proj
  - o_proj
  - gate_proj
  - up_proj
  - down_proj
lora_r: 8
lora_alpha: 16
lora_dropout: 0.05
gptq_use_triton: false

sequence_len: 1024              # 🔽 Reduce sequence length to save memory
sample_packing: false
eval_sample_packing: false
pad_to_sequence_len: false      # 🔽 Also saves padding memory

micro_batch_size: 1             # 🔽 Keep at minimum
gradient_accumulation_steps: 16 # 🔼 Compensate for small batches

num_epochs: 3                   # ⏳ Optional: reduce epoch count for testing
optimizer: adamw_torch
lr_scheduler: cosine
learning_rate: 2e-5
train_on_inputs: false
group_by_length: false

bf16: false
fp16: true
tf32: true

gradient_checkpointing: true    # ✅ Critical for saving memory
save_steps: 10
logging_steps: 5

flash_attention: false
